### ISSUE TITLE
Finding an appropriate development environment

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/GestureIO#1]
Tasks for 1st week.
* We need to decide on hardware (based off what we are shown in class - something with a camera)
* Then find an IDE for the hardware (Unity? Something like that)
* We need libraries that access the webcam, record and analyse the frames for recognizing gestures, and allow access to type text wherever the text cursor is on the screen

**Comment by kevinniland** [comment]
Hardware used: Laptop camera
IDE: Visual Studio Code
Language: Python
