### ISSUE TITLE
Gesture ideas

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/GestureIO#10]
![handSymbols](https://user-images.githubusercontent.com/33293951/75761484-124c6a80-5d31-11ea-9e6b-63d7fa765bd0.PNG)

**Comment by cormacmchale** [comment]
https://medium.com/@blackbird98/sign-language-and-static-gesture-recognition-eaafd6ab00a5
Possible model

**Comment by kevinniland** [comment]
Gestures currently being used are an open hand, peace sign, and fist.

**Comment by kevinniland** [comment]
Initially, we intended to this application to be one where users could perform hand gestures related to the ASL (American Sign Language, which is a natural language that serves as the predominant sign language of Deaf communities in the United States and most of Anglophone Canada). However, we decided to first to make an application that recognises simple, static hand gestures as opposed to hand gestures found in ASL.

**Comment by kevinniland** [comment]
### **Open Hand**
![openhand](https://user-images.githubusercontent.com/26802466/77437879-140fc800-6ddd-11ea-9596-d3783811976f.PNG)

The open hand gesture allows a user to navigate to a URL. The user must first specify a URL in an entry box and then perform the aforementioned gesture.

**Comment by kevinniland** [comment]
### **Fist**
![fist](https://user-images.githubusercontent.com/26802466/77438502-ce9fca80-6ddd-11ea-986f-a8634a6cb651.PNG)

The fist gesture allows a user to open a program/application on their device. The user must first specify a program/application in an entry box and then perform the aforementioned gesture.

**Comment by kevinniland** [comment]
### **Peace Sign**
![peacesign](https://user-images.githubusercontent.com/26802466/77438711-0eff4880-6dde-11ea-97df-645452190ab8.PNG)

#3 The peace sign gesture currently offers no functionality.
