### ISSUE TITLE
Gesture recognition

### ISSUE THREAD

**Issue by cormacmchale** [cormacmchale/GestureIO#3]
This section will document how the program parses and checks frames for gestures and then provides output for printing to screen.

**Comment by kevinniland** [comment]
Gesture recognition complete. User performs a gesture within the area provided on the webcam, image of gesture is converted to numpy array, put through the model, and using neural networks is compared against other gestures. Prediction is then outputted to the user and an action is taken in relation to the gesture.

**Comment by cormacmchale** [comment]
Neural Network Description

**Comment by cormacmchale** [comment]
https://github.com/cormacmchale/GestureIO/issues/6
Shows how the inputs are obtained.

https://github.com/cormacmchale/GestureIO/issues/7
Explains the mapping of the inputs to desired outputs.

Once these steps were complete the model just needs to be pulled into memory at run time.
![model](https://user-images.githubusercontent.com/33293951/77431177-3f41e980-6dd4-11ea-91a7-245f54c75148.PNG)

The prediction of the model is the index of the number with the highest value in the array
![prediction](https://user-images.githubusercontent.com/33293951/77431331-77492c80-6dd4-11ea-87d8-ec68eb13205d.PNG)

Then simply give the model an input and do something based on the output
![decision](https://user-images.githubusercontent.com/33293951/77431446-9f389000-6dd4-11ea-8d54-026a60354b6d.PNG)

**Comment by cormacmchale** [comment]
At run-time for the user it looks like this.
![GUI](https://user-images.githubusercontent.com/33293951/77431671-ee7ec080-6dd4-11ea-9e84-a1db369a6f2a.PNG)
Where the user is shown underneath the image what the Neural Network is deciding is in the box in terms of the gesture.

An update/prediction is performed every 60 frames
![frame](https://user-images.githubusercontent.com/33293951/77431866-356cb600-6dd5-11ea-967f-80c33e3809cc.PNG)

**Comment by cormacmchale** [comment]
1) If you perform 'Open hand'. Then a browser will make a call to whatever URL is typed into the input box.

2) Fist will interact and launch things on the desktop by name (Programs/directories)

3) Peace sign undecided as of yet

4) No recognition... simply does nothing.

NB. if inputs are black then program just informs the user of what gesture it thinks it is seeing. This was designed to let the user become comfortable with the program before performing major outputs.
