### ISSUE TITLE
Accessing the webcam 

### ISSUE THREAD

**Issue by kevinniland** [cormacmchale/GestureIO#5]
This section deals with accessing the webcam of the device.

**Comment by kevinniland** [comment]
* Accessing the webcam via Unity: https://www.youtube.com/watch?v=tEXEe_ikfLw
* Accessing the webcam via Python: https://www.youtube.com/watch?v=1XTqE7LFQjI

**Comment by cormacmchale** [comment]
Screen shot of code used for webcam

**Comment by cormacmchale** [comment]
The webcam just required a simple method call from open CV.
![webcam1](https://user-images.githubusercontent.com/33293951/77433045-c4c69900-6dd6-11ea-9582-5bc130b6a7f6.PNG)
 This begins reading data from the webcam.

All that's required to interact with the data in real time is to grab the frame data at the beginning of a loop. This formed the basis for our image processing/display of continuous Video
![webcam2](https://user-images.githubusercontent.com/33293951/77433218-06efda80-6dd7-11ea-85ba-0f72bf989b9d.PNG)
