### ISSUE TITLE
Extracting an object from an image

### ISSUE THREAD

**Issue by kevinniland** [cormacmchale/GestureIO#6]
Possible solutions: 
* https://www.codementor.io/@innat_2k14/extract-a-particular-object-from-images-using-opencv-in-python-jfogyig5u
* https://www.geeksforgeeks.org/python-pil-image-crop-method/

**Comment by cormacmchale** [comment]
https://docs.opencv.org/3.4/d8/d83/tutorial_py_grabcut.html

**Comment by kevinniland** [comment]
Successfully able to capture specific object from the webcam (gesture being performed) using OpenCV2.

**Comment by cormacmchale** [comment]
As discussed in https://github.com/cormacmchale/GestureIO/issues/7 we decided to use the same process for building the dataset and getting gesture information from the webcam.

**Comment by cormacmchale** [comment]
First and foremost we relied heavily on pre-built openCV image processing functions.
https://opencv.org/
I would recommend anyone to look through this documentation at some point as you will learn loads about how computers can handle and change imagery

**Comment by cormacmchale** [comment]
https://github.com/cormacmchale/GestureIO/blob/master/backend/webcam.py
Is where we learned by messing around with the available tools from openCV

**Comment by cormacmchale** [comment]
![captureImage](https://user-images.githubusercontent.com/33293951/77428553-2df6de00-6dd0-11ea-9e03-1cb8fa4edc76.PNG)
We came up with this solution.
1) Remove background noise (Static Images).
2) Draw outline using edge detection.
3) Allot a space for Gesture capture, for user input and dataset building

**Comment by cormacmchale** [comment]
The code for this is just stacked openCV method calls to achieve what you see above
![stackedcalls](https://user-images.githubusercontent.com/33293951/77430051-7b744a80-6dd2-11ea-8739-26b933e3e299.PNG)

**Comment by cormacmchale** [comment]
To capture the image and convert to pixel data as we needed it we had to crop, save and re-load the image... using PIL(Python Imaging Library)
![PIL](https://user-images.githubusercontent.com/33293951/77430260-c9894e00-6dd2-11ea-89a7-da13c6cb8cb0.PNG)
