### ISSUE TITLE
Building the dataset

### ISSUE THREAD

**Issue by kevinniland** [cormacmchale/GestureIO#7]

**Comment by cormacmchale** [comment]
https://machinelearningmastery.com/how-to-save-a-numpy-array-to-file-for-machine-learning/

**Comment by kevinniland** [comment]
Dataset built. Gestures used to build the dataset include an open hand gesture, peace sign gesture, and fist gesture.

**Comment by cormacmchale** [comment]
https://www.youtube.com/watch?v=sZAlS3_dnk0
In order for the Neural network to be trained we need to obtain a dataset in which to adjust and achieve the right weights and biases for the model to approximate answers with a high enough probability of being correct that we could use it in our program for decision making

**Comment by cormacmchale** [comment]
The simpler the input, the easier the neural network is to train.
So it becomes a question of how to map on the fly pre-processing inputs to a similar shape as whatever training data we were going to use. 
The decision we made was to build our own data set... with an identical shape to our pre-processed data taken from the web cam.

**Comment by cormacmchale** [comment]
See extracting an image for how the pre-processing works
https://github.com/cormacmchale/GestureIO/issues/6

**Comment by cormacmchale** [comment]
We built a dataset by concatinating Image data in a file on a frame by frame basis.
Open CV displays the webcam information to you in this way by default so the environment was already setup.
This way we could press a button on the keyboard while the webcam was running through frames and stack as many number of training images as we needed by moving our hands slowly while this was happening. Moving the hand slowly introduced many different versions of the gesture (robustness)
![captureImage](https://user-images.githubusercontent.com/33293951/77425584-e02ba700-6dca-11ea-9bf4-8f0d9ae31ac2.PNG)

**Comment by cormacmchale** [comment]
How the file looks in raw txt format
![handoutline](https://user-images.githubusercontent.com/33293951/77425681-02252980-6dcb-11ea-8030-82185890ed83.PNG)

**Comment by cormacmchale** [comment]
To train a neural network you simply feed these in one by one and have them mapped to particular out puts. You can hard code the outputs...
To explain.
You tell the Network the the first 300 inputs (open-hand above) should map to the number one. Then the network learns to output a 1 for this type of input vector. We got this from our pre-processing so now our inputs are already the exact shape needed. 
How the output layer looks hard coded.
![outputs](https://user-images.githubusercontent.com/33293951/77427326-161e5a80-6dce-11ea-9640-d25d02545d40.PNG)

**Comment by cormacmchale** [comment]
Once you have an input layer and output layer setup the keras documentation can be followed to train and save/import the model(weights and biases) for use.
https://keras.io/
Code for training the model using a jupyter notebook
https://github.com/cormacmchale/GestureIO/blob/master/neural_network/model.ipynb
To see how the model is used at Runtime
https://github.com/cormacmchale/GestureIO/issues/3
